#!/bin/bash
read -r -p "This will override the database. Do you want to continue? [y/N] " response
response=${response,,} # tolower

if [[ "$response" =~ ^(yes|y)$ ]]; then
    wp db import /var/project/db-dump.sql --path=/var/project/wordpress/wp
fi

