#!/bin/bash
read -r -p "This will override the database. Do you want to continue? [y/N] " response
response=${response,,} # tolower

if [[ "$response" =~ ^(yes|y)$ ]]; then
    ./wp-cli db import db-dump.sql
fi
